version: '3.8'
services:
  postgres:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: data
    ports:
      - "5437:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./dataset:/docker-entrypoint-initdb.d
    restart: always
volumes:
  postgres-data: