gwizd:
  security:
    auth:
      loginUri: /api/oauth2/authorize
      logoutUri: /api/oauth2/logout
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      indent-output: true
  servlet:
    multipart:
      max-file-size: 10MB
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: ${GOOGLE_CLIENT_ID}
#            client-secret: ${GOOGLE_KEY}
springdoc:
  api-docs:
    path: /api/docs
  swagger-ui:
    path: /api/docs.html
