server:
  port: 8081
pathfinder-auth:
  jwt:
    expiration-mins: 15
    secret-key: ${JWT-KEY}
  security:
    loginUri: /api/oauth2/authorize
    logoutUri: /api/oauth2/logout
    redirectUri: /api/docs.html
    allowedRedirectUris:
      http://localhost:8080,
      http://localhost:8081,
      http://localhost:3000
    privileges:
      ROLE_USER:
      ROLE_MODERATOR:
        - AUTHORITY_MODERATOR
      ROLE_ADMIN:
        - AUTHORITY_ADMIN
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      default_schema: pathfinder_auth
  jackson:
    serialization:
      indent-output: true
  servlet:
    multipart:
      max-file-size: 10MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 100928631375-g4vvsd5j7h4cpb14q59cecjsrjftd6f5.apps.googleusercontent.com
            client-secret: ${GOOGLE-KEY}
springdoc:
  api-docs:
    path: /api/docs
  swagger-ui:
    path: /api/docs.html
