server:
  port: 8081
pathfinder-auth:
  security:
    auth:
      loginUri: /api/oauth2/authorize
      logoutUri: /api/oauth2/logout
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      indent-output: true
  servlet:
    multipart:
      max-file-size: 10MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 100928631375-g4vvsd5j7h4cpb14q59cecjsrjftd6f5.apps.googleusercontent.com
            client-secret: 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
springdoc:
  api-docs:
    path: /api/docs
  swagger-ui:
    path: /api/docs.html
