spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      default_schema: pathfinder_backend
  jackson:
    serialization:
      indent-output: true
  servlet:
    multipart:
      max-file-size: 10MB
springdoc:
  api-docs:
    path: /api/docs
  swagger-ui:
    path: /api/docs.html
pathfinder-auth:
  jwt:
    expiration-mins: 15
    secret-key: P8K53KMRFBWDRH3EBWYV3B9MQG6QU8V59PYRWGDG96MNDCYBQCJ5EEGXT5ZF76E6